### ISSUE TITLE
instancable instruments

### ISSUE THREAD

**Issue by dokxid** [dokxid/potato-jam#11]
give an instrument an ui containing:

- piano-roll
  - named sample? idk TBD
- instrument-settings
  - sample loader OR synth settings
  - volume / panning (stuff that tone.js / audiocontext allows)
  - mapped keys

![image](https://github.com/user-attachments/assets/64e2f49c-4afc-4259-8134-86ec4bb00766)

**Comment by daphnelucia** [comment]
🍆LGTF
